import React from 'react';
import Head from 'next/head';
import { Button } from '@material-ui/core';
import reduxWrapper from '@/store';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
      <Button variant="contained" color="primary">
        safad
      </Button>
    </div>
  );
}

// export const getServerSideProps = reduxWrapper.getServerSideProps(
//   (store) =>
//     async ({ params }) => {
//       console.log(store);
//       return {
//         props: {
//           a: true,
//         },
//       };
//     },
// );
